<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.chromia</groupId>
        <artifactId>chromia-parent</artifactId>
        <version>0.2.4</version>
    </parent>

    <groupId>net.postchain</groupId>
    <artifactId>postchain-eif</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <modules>
        <module>postchain-eif-contracts</module>
        <module>postchain-eif-core</module>
        <module>postchain-eif-rell</module>
    </modules>

    <name>postchain-eif</name>
    <description>Postchain EIF. Ethereum Integration Framework</description>

    <properties>
        <revision>dev</revision>
        <postchain.version>3.49.3</postchain.version>
        <rell.version>0.15.0</rell.version>
        <kotlin.version>2.3.0</kotlin.version>
        <rell.maven.plugin.version>0.16.5</rell.maven.plugin.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <kotlin.compiler.jvmTarget>21</kotlin.compiler.jvmTarget>
        <testcontainers.version>2.0.2</testcontainers.version>
        <junit.pioneer.version>2.2.0</junit.pioneer.version>
        <web3j.version>4.13.0</web3j.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.postchain</groupId>
                <artifactId>postchain</artifactId>
                <version>${postchain.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>

            <dependency>
                <groupId>org.web3j</groupId>
                <artifactId>core</artifactId>
                <version>${web3j.version}</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>4.9.3</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okio</groupId>
                <artifactId>okio</artifactId>
                <version>3.4.0</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>logging-interceptor</artifactId>
                <version>4.9.3</version>
            </dependency>

            <!-- Tests -->
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-junit-jupiter</artifactId>
                <version>${testcontainers.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.junit-pioneer</groupId>
                <artifactId>junit-pioneer</artifactId>
                <version>${junit.pioneer.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-gtx</artifactId>
                <version>${rell.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults -->
            <plugins>
                <plugin>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-maven-plugin</artifactId>
                    <version>${kotlin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.web3j</groupId>
                    <artifactId>web3j-maven-plugin</artifactId>
                    <version>${web3j.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.owasp</groupId>
                    <artifactId>dependency-check-maven</artifactId>
                    <configuration>
                        <prettyPrint>true</prettyPrint>
                        <failBuildOnAnyVulnerability>true</failBuildOnAnyVulnerability>
                        <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
                        <yarnAuditAnalyzerEnabled>false</yarnAuditAnalyzerEnabled>
                        <suppressionFiles>
                            <suppressionFile>https://gitlab.com/chromaway/chromia-parent/-/raw/dev/common-dependencies-suppression.xml?ref_type=heads</suppressionFile>
                            <suppressionFile>dependencies-suppression.xml</suppressionFile>
                        </suppressionFiles>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>net.postchain.rell</groupId>
                    <artifactId>rell-maven-plugin</artifactId>
                    <version>${rell.maven.plugin.version}</version>
                    <configuration>
                        <hideLibWarnings>true</hideLibWarnings>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-deps</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <includeScope>runtime</includeScope>
                            <outputDirectory>${project.build.directory}/lib</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>**/*IT.java</exclude>
                        <exclude>**/*SlowIntegrationTest.java</exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <configuration>
                    <includes>
                        <include>**/*IT.java</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>chromia-parent</id>
            <name>Chromia parent GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/50818999/packages/maven</url>
        </repository>
        <repository>
            <id>postchain</id>
            <name>Postchain GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/32294340/packages/maven</url>
        </repository>
        <repository>
            <id>rell</id>
            <name>Rell Registry</name>
            <url>https://gitlab.com/api/v4/projects/32802097/packages/maven</url>
        </repository>
        <repository>
            <id>postchain-client</id>
            <name>Postchain Client GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/46288950/packages/maven</url>
        </repository>
        <repository>
            <id>central</id>
            <name>Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
            <layout>default</layout>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <!-- Needed for web3j -->
        <repository>
            <id>consensys</id>
            <name>Consensys repository</name>
            <url>https://artifacts.consensys.net/public/maven/maven/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>rellmaven</id>
            <url>https://gitlab.com/api/v4/projects/37668820/packages/maven</url>
        </pluginRepository>
    </pluginRepositories>

    <distributionManagement>
        <repository>
            <id>gitlab-maven</id>
            <!--suppress UnresolvedMavenProperty -->
            <url>https://gitlab.com/api/v4/projects/36768178/packages/maven</url>
        </repository>
        <snapshotRepository>
            <id>gitlab-maven</id>
            <!--suppress UnresolvedMavenProperty -->
            <url>https://gitlab.com/api/v4/projects/36768178/packages/maven</url>
        </snapshotRepository>
    </distributionManagement>
</project>
