---
# Price oracle - eventsUniswapV2.yaml
- anonymous: 0
  inputs:
    - indexed: 0
      internalType: uint112
      name: reserve0
      type: uint112
    - indexed: 0
      internalType: uint112
      name: reserve1
      type: uint112
  name: Sync
  type: event

# Price oracle - Uniswap V3 Swap
- anonymous: 0
  inputs:
    - indexed: 1
      internalType: address
      name: sender
      type: address
    - indexed: 1
      internalType: address
      name: recipient
      type: address
    - indexed: 0
      internalType: int256
      name: amount0
      type: int256
    - indexed: 0
      internalType: int256
      name: amount1
      type: int256
    - indexed: 0
      internalType: uint160
      name: sqrtPriceX96
      type: uint160
    - indexed: 0
      internalType: uint128
      name: liquidity
      type: uint128
    - indexed: 0
      internalType: int24
      name: tick
      type: int24
    - indexed: 0
      internalType: uint128
      name: protocolFeesToken0
      type: uint128
    - indexed: 0
      internalType: uint128
      name: protocolFeesToken1
      type: uint128
  name: Swap
  type: event
