definitions:
  - &eif_test
    chains:
      goerli:
        network_id: 5
        contracts:
          - '0xb7eb5d60dd5610a82a4844beb3f7d750316d3d32'
        skip_to_height: 9149852
        events: !include configs/events.yml
  - &common_args
    lib.ft4.accounts:
      rate_limit_active: true
      rate_limit_max_points: 200
      rate_limit_recovery_time: 5000
      rate_limit_points_at_account_creation: 100
  - &rell_test_args
    lib.ft4.admin:
      admin_pubkey: 02897FAC9964FBDF97E6B83ECCBDE4A8D28729E0FB27059487D1B6B29F70B48767
    lib.access.admin:
      admin_pubkey: 02897FAC9964FBDF97E6B83ECCBDE4A8D28729E0FB27059487D1B6B29F70B48767
    lib.originals.marketplace:
      oracle_pubkey: 02897FAC9964FBDF97E6B83ECCBDE4A8D28729E0FB27059487D1B6B29F70B48767

test:
  modules:
    - tests.originals
  moduleArgs:
    <<: *common_args
    <<: *rell_test_args

blockchains:
  eif:
    module: main
    config:
      gtx:
        modules: ['net.postchain.eif.EifGTXModule']
      eif:
        <<: *eif_test
      sync_ext: ['net.postchain.eif.EifSynchronizationInfrastructureExtension']
    moduleArgs:
      <<: *common_args
      <<: *rell_test_args

compile:
  source: src
  target: target
  rellVersion: 0.13.5
libs:
  ft4:
    registry: https://bitbucket.org/chromawallet/ft3-lib
    path: rell/src/lib/ft4
    tagOrBranch: v0.1.7r
    rid: x"AF18D94EC9B01F9FD82BCE6B12F68D83CF19C9E2B2CDFB49C8AA2C9AA38B31B4"
    insecure: false
  iccf:
    registry: https://gitlab.com/chromaway/core/directory-chain
    path: src/iccf
    tagOrBranch: 1.9.1
    rid: x"593D6EBA650BAC473E105C047B2C43A099164870304B3E5E324F714FF2F3F82F"
    insecure: false
  pagination:
    registry: https://bitbucket.org/chromawallet/lib-pagination-utils
    path: rell/src/core/pagination
    tagOrBranch: master
    insecure: true
  access:
    registry: ${ORIGINALS_REPO:-git@bitbucket.org:chromawallet/originals-dip.git}
    path: rell/src/access
    tagOrBranch: dev
    insecure: true
  dip:
    registry: ${ORIGINALS_REPO:-git@bitbucket.org:chromawallet/originals-dip.git}
    path: rell/src/dip
    tagOrBranch: dev
    insecure: true
  evm_accounts:
    registry: ${ORIGINALS_REPO:-git@bitbucket.org:chromawallet/originals-dip.git}
    path: rell/src/evm_accounts
    tagOrBranch: dev
    insecure: true
  originals:
    registry: ${ORIGINALS_REPO:-git@bitbucket.org:chromawallet/originals-dip.git}
    path: rell/src/originals
    tagOrBranch: dev
    insecure: true
  projects:
    registry: ${ORIGINALS_REPO:-git@bitbucket.org:chromawallet/originals-dip.git}
    path: rell/src/projects
    tagOrBranch: dev
    insecure: true
  collections:
    registry: ${ORIGINALS_REPO:-git@bitbucket.org:chromawallet/originals-dip.git}
    path: rell/src/collections
    tagOrBranch: dev
    insecure: true
  common:
    registry: ${ORIGINALS_REPO:-git@bitbucket.org:chromawallet/originals-dip.git}
    path: rell/src/common
    tagOrBranch: dev
    insecure: true
  ft_helper:
    registry: ${ORIGINALS_REPO:-git@bitbucket.org:chromawallet/originals-dip.git}
    path: rell/src/ft_helper
    tagOrBranch: dev
    insecure: true
    