definitions:
  - &eif_test
    chains:
      goerli:
        network_id: 5
        contracts:
          - '0xb7eb5d60dd5610a82a4844beb3f7d750316d3d32'
        skip_to_height: 9149852
  - &common_args
    lib.ft3.core:
      my_blockchain_name: My Neighbor Alice
      my_blockchain_website: https://myneighboralice.com
      my_blockchain_description: My Neighbor Alice is a multiplayer builder game, introducing blockchain to millions of players. Anyone can buy and own virtual islands, collect and build exciting items and meet new friends.
      rate_limit_active: 0
      rate_limit_max_points: 20
      rate_limit_recovery_time: 5000
      rate_limit_points_at_account_creation: 20
  - &rell_test_args
    lib.originals.marketplace:
      oracle_pubkey: 02a829e1d7fffbd856a04b53ec7d478d8896803b571c7700ec464d6a9d4f0e3bbd
    lib.access.admin:
      admin_pubkey: 0350fe40766bc0ce8d08b3f5b810e49a8352fdd458606bd5fafe5acdcdc8ff3f57
    eif:
      sync_transfers_inside_dapp: true

test:
  modules:
    - tests.eif
  moduleArgs:
    <<: *common_args
    <<: *rell_test_args

blockchains:
  eif:
    module: main
    config:
      gtx:
        modules: ['net.postchain.eif.EifGTXModule']
      eif:
        <<: *eif_test
      sync_ext: ['net.postchain.eif.EifSynchronizationInfrastructureExtension']
    moduleArgs:
      <<: *common_args
      <<: *rell_test_args

compile:
  source: src
  rellVersion: 0.10.11
libs:
  ft3:
    registry: https://bitbucket.org/chromawallet/ft3-lib/src/v2.1.0/
    path: rell/src/lib/ft3
    tagOrBranch: ft3.5
    rid: x"4F31FF92307C464BBCF8970A293BF6A5B91600921EA727825F401801649BDE72"
  access:
    registry: ${ORIGINALS_REPO:-git@bitbucket.org:chromawallet/originals-dip.git}
    path: rell/src/access
    tagOrBranch: eif
    rid: x"67FCAF1E65709EEB03B11820FC62D99C784D0B45A52F0C06CE54FA4389033F5D"
  dip:
    registry: ${ORIGINALS_REPO:-git@bitbucket.org:chromawallet/originals-dip.git}
    path: rell/src/dip
    tagOrBranch: eif
    rid: x"0410477041210AACC96A1E6B5495E9004B8FEE6F6CA12A858776A3C19C61BD8D"
  evm_accounts:
    registry: ${ORIGINALS_REPO:-git@bitbucket.org:chromawallet/originals-dip.git}
    path: rell/src/evm_accounts
    tagOrBranch: eif
    rid: x"D67D442DBB2E6CBB1FD0656D8B30C6FFC063403E5DE76F751ACD7D3F0F731369"
  originals:
    registry: ${ORIGINALS_REPO:-git@bitbucket.org:chromawallet/originals-dip.git}
    path: rell/src/originals
    tagOrBranch: eif
    rid: x"1A5F24EDFEBB46B89F41E4AD7CDD4EC538372EE0FF953BD8BE1490FBFB9ED7F1"

