definitions:
  - &eif_test
    chains:
      goerli:
        network_id: 5
        contracts:
          - '0xb7eb5d60dd5610a82a4844beb3f7d750316d3d32'
        skip_to_height: 9149852
        events: !include configs/events.yml
  - &common_args
    lib.ft4.accounts:
      rate_limit_active: true
      rate_limit_max_points: 200
      rate_limit_recovery_time: 5000
      rate_limit_points_at_account_creation: 100
  - &rell_test_args
    lib.ft4.admin:
      admin_pubkey: 0350fe40766bc0ce8d08b3f5b810e49a8352fdd458606bd5fafe5acdcdc8ff3f57
    eif:
      sync_transfers_inside_dapp: true

test:
  modules:
    - tests.eif
  moduleArgs:
    <<: *common_args
    <<: *rell_test_args

blockchains:
  eif:
    module: main
    config:
      gtx:
        modules: ['net.postchain.eif.EifGTXModule']
      eif:
        <<: *eif_test
      sync_ext: ['net.postchain.eif.EifSynchronizationInfrastructureExtension']
    moduleArgs:
      <<: *common_args
      <<: *rell_test_args

compile:
  source: src
  target: target
  rellVersion: 0.10.11
libs:
  ft4:
    registry: https://bitbucket.org/chromawallet/ft3-lib
    path: rell/src/lib/ft4
    tagOrBranch: development
    rid: x"37DE200177CD28986F87F6DD490C14C23754B876831B88F90AE23EB2F43347A4"
    insecure: false